language: node_js
node_js:
  - "4.4.7"
before_install:
  - "npm install -g bower"
  - "bower install"
  - "npm install -g web-component-tester"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "wct"
deploy:
  provider: script
  script: "bash ./gpages.sh cheonhyangzhang paper-typeahead-input"
  on:
    branch: release
